// Real dashboard event handlers and IndexedDB with a DOM implementation.
// Media decoding/clipboard/canvas are controlled; browser codec support isn't simulated.
import fs from 'node:fs';import {JSDOM} from 'jsdom';import {IDBFactory} from 'fake-indexeddb';import assert from 'node:assert/strict';
const dir=new URL('../paper-terminal-extension/',import.meta.url);
const html=fs.readFileSync(new URL('dashboard.html',dir),'utf8').replace(/<script[^>]*><\/script>/g,'');
const dom=new JSDOM(html,{url:'https://fixture.test/dashboard.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
w.structuredClone=structuredClone;w.indexedDB=new IDBFactory();w.URL.createObjectURL=()=>`blob:test-${Math.random()}`;w.URL.revokeObjectURL=()=>{};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
w.Image=class{constructor(){this.naturalWidth=1600;this.naturalHeight=1000;}set src(v){this._src=v;queueMicrotask(()=>this.onload?.());}};
w.ImageDecoder=class {static async isTypeSupported(){return true;}constructor(){this.tracks={ready:Promise.resolve(),selectedTrack:{frameCount:1}};}async decode(){return {image:{displayWidth:100,displayHeight:100,duration:100000,close(){}}};}close(){}};
w.HTMLMediaElement.prototype.play=async()=>{};w.HTMLMediaElement.prototype.pause=()=>{};
Object.defineProperty(w.HTMLMediaElement.prototype,'src',{set(value){this._src=value;queueMicrotask(()=>this.onloadeddata?.());},get(){return this._src;}});
const paints=[];const context={save(){},restore(){},beginPath(){},moveTo(){},lineTo(){},closePath(){},fill(){},clearRect(){},fillRect(){},drawImage(){},fillText(text){paints.push(text);},measureText(text){return{width:text.length*18}},createLinearGradient(){return{addColorStop(){}}}};
w.HTMLCanvasElement.prototype.getContext=()=>context;w.HTMLCanvasElement.prototype.toBlob=cb=>cb(new Blob(['png'],{type:'image/png'}));
w.HTMLAnchorElement.prototype.click=function(){downloads.push({href:this.href,name:this.download});};
let clipboardWrites=0;w.ClipboardItem=class{constructor(v){this.value=v;}};Object.defineProperty(w.navigator,'clipboard',{value:{async write(){clipboardWrites++;}}});
const downloads=[];const intervals=[];w.setInterval=fn=>intervals.push(fn);
w.eval(fs.readFileSync(new URL('mock-dashboard.js',import.meta.url),'utf8'));
for(const file of ['trade-settings.js','portfolio-data.js','pnl-cards.js','dashboard.js'])w.eval(fs.readFileSync(new URL(file,dir),'utf8'));
const doc=w.document,click=selector=>{const node=doc.querySelector(selector);assert.ok(node,selector);node.click();};
async function until(predicate){const deadline=Date.now()+3000;while(!predicate()){if(Date.now()>deadline)throw new Error('Timed out waiting for dashboard state');await new Promise(r=>setTimeout(r,5));}}
await until(()=>doc.querySelectorAll('.data-row').length>0);
let passed=0;async function test(name,run){await run();passed++;console.log('PASS '+name);}
await test('one main page contains positions/history without Settings, Activity or Transfers tabs',()=>{assert.equal(doc.querySelectorAll('.table-tabs button').length,2);assert.ok(doc.querySelector('#overview'));assert.ok(!/paper\s*trad/i.test(doc.body.textContent));assert.ok(![...doc.querySelectorAll('button')].some(n=>/^(Settings|Activity|Transfers)$/.test(n.textContent)));assert.equal(doc.querySelectorAll('.data-row').length,3)});
await test('History exposes old rounds and buy/sell details',()=>{click('[data-tab="history"]');assert.equal(doc.querySelectorAll('.data-row').length,18);click('[data-expand]');assert.equal(doc.querySelectorAll('.detail-row .fill-item').length,2);assert.match(doc.querySelector('.detail-row').textContent,/Buy/);assert.match(doc.querySelector('.detail-row').textContent,/Sell/)});
await test('search filters rows without losing the active search input',()=>{const search=doc.querySelector('#search');search.value='NO-SUCH-TOKEN';search.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(doc.querySelectorAll('.data-row').length,0);assert.equal(doc.querySelector('#empty-state').hidden,false);search.value='';search.dispatchEvent(new w.Event('input',{bubbles:true}));assert.equal(doc.querySelectorAll('.data-row').length,18)});
await test('timeframe controls update persisted range and chart title',async()=>{click('[data-range="7d"]');assert.match(doc.querySelector('.chart-panel h2').textContent,/7D/);assert.equal((await w.chrome.storage.local.get('paperTerminalPortfolioPrefs')).paperTerminalPortfolioPrefs.range,'7d')});
await test('calendar day opens its dated card and retains drill-down transactions',async()=>{click('[data-calendar]');assert.equal(doc.querySelector('#calendar-dialog').open,true);const day=[...doc.querySelectorAll('[data-day]')].find(n=>n.textContent.includes('txns'));assert.ok(day);day.click();assert.ok(doc.querySelector('.day-detail'));assert.ok(doc.querySelectorAll('.day-detail .fill-item').length>=1);await until(()=>doc.querySelectorAll('[data-background]').length===6&&doc.querySelector('#card-status')?.textContent==='');assert.equal(doc.querySelector('#card-dialog').open,true);const date=new Date(day.dataset.day+'T12:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'});assert.ok(paints.includes(date));assert.ok(paints.includes('Buy Volume'));assert.ok(!paints.some(t=>/\bSOL\b|Fees/.test(t)));click('[data-close-card]')});
await test('month navigation changes the month without leaving the page',()=>{const before=doc.querySelector('.calendar-navigation strong').textContent;click('[data-month="-1"]');assert.notEqual(doc.querySelector('.calendar-navigation strong').textContent,before);click('[data-month="1"]')});
await test('monthly P&L opens a nested card with cash boundaries',async()=>{click('[data-share-month]');await until(()=>doc.querySelectorAll('[data-background]').length===6&&doc.querySelector('#card-status').textContent==='');assert.equal(doc.querySelector('#card-dialog').open,true);assert.ok(paints.includes('Start cash'));assert.ok(paints.includes('End cash'));click('[data-close-card]');assert.equal(doc.querySelector('#calendar-dialog').open,true);click('[data-close-calendar]')});
await test('every trade has a card with six locally bundled photo choices',async()=>{paints.length=0;click('[data-share-round]');await until(()=>doc.querySelectorAll('[data-background]').length===6&&doc.querySelector('#card-status').textContent==='');assert.equal(doc.querySelectorAll('.background-choice img').length,6);assert.equal(doc.querySelector('#pnl-canvas').width,1200);assert.ok(!paints.includes('Transactions'));assert.ok(!paints.includes('Holding'));assert.ok(paints.includes('Invested'));assert.ok(paints.includes('Position'));assert.ok(!paints.some(text=>/paper\s*trad|closed trade/i.test(text)))});
await test('background and card name persist across closing and reopening',async()=>{click('[data-background="forest"]');await until(()=>doc.querySelector('[data-background="forest"]').classList.contains('active'));const input=doc.querySelector('#card-handle');input.value='Tester';input.dispatchEvent(new w.Event('input',{bubbles:true}));await w.PnlCards.preferences();click('[data-close-card]');click('[data-share-round]');await until(()=>doc.querySelector('[data-background="forest"]')?.classList.contains('active'));assert.equal(doc.querySelector('#card-handle').value,'Tester')});
await test('upload GIF saves original media and restores it after reopening',async()=>{const input=doc.querySelector('#media-upload');const file=new File(['GIF89a'],'custom.gif',{type:'image/gif'});Object.defineProperty(input,'files',{value:[file],configurable:true});input.dispatchEvent(new w.Event('change',{bubbles:true}));await until(()=>doc.querySelectorAll('[data-background]').length===7&&doc.querySelector('#card-status').textContent==='');const assets=await w.PnlCards.list();assert.equal(assets.length,1);assert.equal(assets[0].type,'image/gif');assert.equal(assets[0].blob.size,file.size);const id=assets[0].id;click('[data-close-card]');click('[data-share-round]');await until(()=>doc.querySelector(`[data-background="${id}"]`)?.classList.contains('active'))});
await test('video upload is persisted separately from trading state',async()=>{const before=await w.chrome.storage.local.get('paperTerminalState');const file=new File(['video'],'clip.webm',{type:'video/webm'});const asset=await w.PnlCards.save(file);assert.equal(asset.type,'video/webm');assert.equal((await w.PnlCards.list()).length,2);assert.deepEqual(await w.chrome.storage.local.get('paperTerminalState'),before)});
await test('unsupported and oversize uploads never replace saved media',async()=>{await assert.rejects(w.PnlCards.save(new File(['<svg/>'],'bad.svg',{type:'image/svg+xml'})),/Choose/);await assert.rejects(w.PnlCards.save({size:101*1024*1024,type:'image/png'}),/100 MB/);assert.equal((await w.PnlCards.list()).length,2)});
await test('simultaneous preference edits retain background, unit and name',async()=>{await Promise.all([w.PnlCards.preferences({unit:'USD'}),w.PnlCards.preferences({name:'Saved name'}),w.PnlCards.preferences({background:'highlands'})]);const p=await w.PnlCards.preferences();assert.equal(p.unit,'USD');assert.equal(p.name,'Saved name');assert.equal(p.background,'highlands')});
await test('font upload persists separately, reloads, and rejects broken files before replacing it',async()=>{
 const faces=new Set();w.document.fonts={add:f=>faces.add(f),delete:f=>faces.delete(f)};w.FontFace=class{constructor(family,bytes){this.family=family;this.bytes=bytes;}async load(){return this;}};
 const file=new File([new Uint8Array([79,84,84,79,0,1,2,3])],'Univers.otf',{type:'font/otf'});
 const before=await w.chrome.storage.local.get('paperTerminalState');const font=await w.PnlCards.saveFont(file);assert.equal(font.family,'TerminalUnivers');assert.equal(faces.size,1);
 w.eval(fs.readFileSync(new URL('pnl-cards.js',dir),'utf8'));assert.equal((await w.PnlCards.loadFont()).family,'TerminalUnivers');
 await assert.rejects(w.PnlCards.saveFont(new File(['not a font'],'bad.otf')),/not a supported font/);assert.deepEqual(await w.chrome.storage.local.get('paperTerminalState'),before);
});
await test('PNG export and copy execute from the visible card controls',async()=>{click('#copy-card');await until(()=>clipboardWrites===1);click('#download-card');await until(()=>downloads.length===1);assert.match(downloads[0].name,/\.png$/)});
await test('video mode disables image copy and gives its duration/format',()=>{click('[data-mode="video"]');assert.equal(doc.querySelector('#copy-card').disabled,true);assert.match(doc.querySelector('#card-status').textContent,/8-second WebM/)});
await test('live account changes leave a card draft intact',async()=>{const input=doc.querySelector('#card-handle');input.value='Uninterrupted';input.dispatchEvent(new w.Event('input',{bubbles:true}));const saved=(await w.chrome.storage.local.get('paperTerminalState')).paperTerminalState;saved.balanceUsd+=1;await w.chrome.storage.local.set({paperTerminalState:saved});await new Promise(r=>setTimeout(r,180));assert.equal(doc.querySelector('#card-handle').value,'Uninterrupted');assert.equal(doc.querySelector('#card-dialog').open,true)});
await test('token names are escaped instead of becoming HTML',async()=>{click('[data-close-card]');const saved=(await w.chrome.storage.local.get('paperTerminalState')).paperTerminalState;for(const p of Object.values(saved.positions))p.token.symbol='<img id="injected">';await w.chrome.storage.local.set({paperTerminalState:saved});await new Promise(r=>setTimeout(r,180));assert.equal(doc.querySelector('#injected'),null);assert.ok(doc.querySelector('#trade-rows').textContent.includes('<img id="injected">'))});
dom.window.close();console.log(`${passed} dashboard/media flow tests passed`);
